DROP TABLE IF EXISTS jobs CASCADE;
CREATE TABLE jobs (
  id SERIAL PRIMARY KEY,
  revision VARCHAR(32) DEFAULT '-',
  test_tag VARCHAR(64) NOT NULL,
  build_tag VARCHAR(64) NOT NULL,
  job_status VARCHAR(32) DEFAULT 'new',
  build_flags VARCHAR(256) DEFAULT 'none',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TABLE IF EXISTS logs CASCADE;
CREATE TABLE logs (
  id SERIAL PRIMARY KEY,
  job_id INTEGER REFERENCES jobs(id) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TABLE IF EXISTS stacks CASCADE;
CREATE TABLE stacks (
  id SERIAL PRIMARY KEY,
  log_id INTEGER REFERENCES logs(id) NOT NULL,
  frequency SMALLINT DEFAULT 1,
  frames VARCHAR(1024) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
